<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Personal extends Model
{
    use HasFactory;

    protected $table = 'sw_MIGRA_PERSONAL';
    protected $primaryKey = 'CODI_PERS';
    public $timestamps = false;

    protected $fillable = [
        'CODI_PERS',
        'CODI_TIPO_DOCU',
        'NRO_DOCU_IDEN',
        'APEL_1',
        'APEL_2',
        'NOMB_1',
        'NOMB_2',
        'CODI_SIST_PENS',
        'SIST_PENS_TIPOCOMI',
        'CODI_CARG',
        'CODI_AREA',
        'CODI_MONE_BASI',
        'SUEL_BASI',
        'FECH_INGRE_PLANILLA',
        'FECH_INGRE',
        'ESSALUD',
        'CARN_ESSALUD',
        'ESTA_CIVI',
        'FECH_NACI',
        'ASIG_FAMI',
        'ESTA_ACTI',
        'SCRT',
        'COMI_PESC',
        'NRO_CUPSS',
        'AFIL_SIND',
        'NRO_FICHA',
        'TIPO_CONT',
        'CODI_MONE',
        'SUEL_NETO',
        'CARG_FAMI',
        'SEXO',
        'NACIONALIDAD',
        'DIRECCION',
        'PERS_EMAIL',
        'TIPO_SITU_LABO',
        'SEGU_VIDA_LEY',
        'PERS_CONBREVETE',
        'PERS_BREVETE',
        'FECH_CESE',
        'CLAVE',
        'JUBILADO',
        'FORM_PAGO',
        'CODI_ANTI',
        'MONT_PAGO_COME',
        'HORA_LABO',
        'CODI_UNID_OPER',
        'PERS_FECHEMISIONDNI',
        'PERS_FECHCADUCADNI',
        'CODI_RELA',
        'MOTI_CESE',
        'PROVINCIA',
        'DISTRITO',
        'VCMTO',
        'DEPARTAMENTO',
        'OBSERVACIONES',
        'CODI_TIPO_RIES',
        'UBIGEO',
        'FOTO_SI_NO',
        'FECH_INIC_AFIL',
        'DIST_NACI',
        'PROV_NACI',
        'UTIL03',
        'CODI_AREA_GRUP',
        'CODI_SUB_AREA_GRUP',
        'HORA_AUTO',
        'GRAT',
        'VACA',
        'codi_luga_trab',
        'AFECTO_LEY',
        'fotocheck',
        'horario',
        'CODI_CATE_TRAB',
        'ESCI_CODIGO',
        'DEPA_CODIGO_NACI',
        'PROVI_CODIGO_NACI',
        'DEPA_CODIGO_DOMI',
        'PROVI_CODIGO_DOMI',
        'apor_essa',
        'apor_sena',
        'apor_senc',
        'apor_cona',
        'tipo_sangr',
        'peso_kilo',
        'tall_metr',
        'PERS_LUEXPDNI',
        'PERS_NRORUC',
        'PERS_NROLIBM',
        'PERS_CONYUGE',
        'PERS_CONHIJOS',
        'PERS_PROFESION',
        'PERS_NROANTPOL',
        'PERS_NORANTPEN',
        'PERS_CTRABANT',
        'PERS_CARGOTRABANT',
        'PERS_DURACIONANT',
        'PERS_SNADAR',
        'PERS_CONSMO',
        'PERS_LUGARSMO',
        'PERS_CONDISCAMEC',
        'PERS_NRODISCAMEC',
        'PERS_CONLICARMAS',
        'PERS_NROLICENCIA',
        'PERS_CONARMAS',
        'PERS_SERIEARMA',
        'PERS_TIPOARMA',
        'PERS_ACEPTADTA',
        'PERS_NROEMERGENCIA',
        'PERS_NOMCONTACTO',
        'PERS_FECHAREG',
        'PERS_VIGENCIA',
        'USUA_CODIGO',
        'PERS_TELEFONO',
        'PERS_MARCA',
        'PERS_CALIBRE',
        'PERS_MODELO',
        'PERS_TIPOTRAB',
        'PERS_CONTRATADO',
        'EMPR_CODIGO',
        'SUCU_CODIGO',
        'USUA_CODIGO_REG',
        'USUA_FECHA_REG',
        'USUA_CODIGO_MOD',
        'USUA_FECHA_MOD',
        'PERS_FECHARETIRO',
        'PERS_FLAG',
        'cala_codigo',
        'Pers_fech_venc_lic_arm',
        'PERS_OBSERVACIONES',
        'PERS_RESERVA',
        'EMPRESA_ASOCIADA_5TA',
        'MOCE_CODIGO',
        'PERS_ACTUALIZAR',
        'PERS_SEXO',
        'PERS_GRADO_INSTRUCCION',
        'PERS_DIREC_DNI',
        'CONTROL_MIGRADO',
        'PERS_PARA_FOTOCHECK',
        'PERS_CON_FOTOCHECK',
        'PERS_VERIF_RENIEC',
        'PERS_VERIF_USUARIO',
        'PERS_VERIF_FECHA',
        'PERS_DPTO_DIRDNI',
        'PERS_PROV_DIRDNI',
        'PERS_DIST_DIRDNI',
        'GRADO_INSTRUC_OBS',
        'OBS_CESE',
        'CONTROL_MIGRADO2',
        'PERS_PENSIONISTA',
        'PERS_OMISO_ONPE',
        'USUA_MOD_PLAN',
        'FEC_MOD_PLAN',
        'CONTROL_MIGRADO_COPE',
        'CONTROL_MIGRADO_AUSTRAL',
        'CONTROL_MIGRADO_CONSORCIO',
        'CONTROL_MIGRADO_CODRALUX',
        'CONTROL_VERIF_TRANS',
        'TIZO_CODIGO',
        'PERS_ZONA_DIRDNI',
        'PERS_KM_MZ_DIRDNI',
        'PERS_LOTE_DIRDNI',
        'PERS_NRO_DIRDNI',
        'PERS_KM_DIRDNI',
        'PERS_MZ_DIRDNI',
        'IEDU_CODIGO',
        'CARR_CODIGO',
        'EGRESO_EDUCATIVO',
        'PERS_TRABAJO_ANTERIOR',
        'CODI_TIPO_DOCU_ANT',
        'CLASE_BREVETE',
        'CATEGORIA_BREVETE',
        'FECH_EXP_BREVETE',
        'FECH_REVAL_BREVETE',
        'RESTRICCION_BREVETE',
    ];


    public function telefonos()
    {
        return $this->hasMany(Telefono::class, 'CODI_PERS', 'CODI_PERS');
    }

    public function derechoHabientes()
    {
        return $this->hasMany(DerechoHabiente::class, 'CODI_PERS', 'CODI_PERS');
    }
}
